### ISSUE TITLE
missing assets and errors in clean install

### ISSUE THREAD

**Issue by Muphet** [suriyun-production/turnbase-rpg-docs#5]
```Assets/RPGGame/Core/Scripts/GameService/Implement/WebServiceClient/WebServiceClient.cs(187,26): error CS1061: Type `UnityEngine.Networking.UnityWebRequest' does not contain a definition for `SendWebRequest' and no extension method `SendWebRequest' of type `UnityEngine.Networking.UnityWebRequest' could be found. Are you missing an assembly reference?```
this error shows up in clean install import. I figured out i am supposed to use send() instead but this is not everything. There is a lot of missing assets and prefabs such as login panels.
additionally, when trying to conenct to external host, there is an error:
```
[GET->Error]/service-time Cannot connect to destination host 
UnityEngine.Debug:LogError(Object)
<GetRoutine>c__Iterator0:MoveNext() (at Assets/RPGGame/Core/Scripts/GameService/Implement/WebServiceClient/WebServiceClient.cs:190)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

**Comment by insthync** [comment]
Which is your Unity version, As I test `SendWebRequest` is work for Unity 2018.2.21 / 2019.2.8, and as I see, `Send` function is in older Unity version.

About `Cannot connect to destination host`
I want to see your `Service Url` setting.

For overall, I think, You should use Unity version 2018.2.21 or higher

**Comment by Muphet** [comment]
yes i figured out all assets work fine on 2018.2.21 but 2019 breaks most of the things and you have to manually add missing things. I think you should add info to asset what unity version should be used or update for latest version so it could be imported properly in 2019
